service: qusasat-telegram-sender

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  deploymentMethod: direct
  environment:
    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}
    TELEGRAM_CHAT_ID: ${env:TELEGRAM_CHAT_ID}
    MESSAGES_SIGNATURE: ${env:MESSAGES_SIGNATURE}
  httpApi:
    cors: true
  logs:
    httpApi: true

functions:
  cronHandler:
    handler: telegram_sender.lambda_run
    events:
      - schedule:
          # Everyday at 5pm UTC
          rate: cron(0 17 * * ? *)
          enabled: true
  httpHandler:
    handler: handler.run
    events:
      - httpApi:
          path: /
          method: 'get'

# Install nodejs 19 then run: npm install
plugins:
  - serverless-python-requirements
