name: HerokuDeploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: false
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_email: heroku@hammady.net
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: qusasat
